[service]
name = "Orange Pi Zero 3 KVM"
token_file = "/etc/hidmi/token"
discovery_udp_port = 55536
timeout_offer_ttl_sec = 5
timeout_tcp_sec = 6.0

[board]
hid_keyboard_path = "/dev/hidg0"
hid_mouse_path = "/dev/hidg1"
hid_absolute_mouse_path = "/dev/hidg2"
udc_state_path = "/sys/class/udc/musb-hdrc.5.auto/state"

[board.leds]
enabled = true
primary = "/sys/class/leds/green_led"
secondary = "/sys/class/leds/red_led"
