syntax = "proto3";

package hidmi.kvm.input.v1;

import "enum_interface_type.proto";
import "enum_hid_status.proto";

message Discover {
  fixed64 server_id = 1;
  fixed64 boot_id = 2;
  string server_name = 3;
  InterfaceType interface_type = 4;

  fixed32 tcp_accept_min = 10;
  fixed32 tcp_accept_max = 11;
  repeated fixed32 tcp_rejected = 12;

  bytes challenge_nonce = 20;
  bool is_busy = 21;
  HidStatus hid_status = 22;
  bool hid_available = 23;
  bool absolute_pointer_available = 24;
  bool relative_pointer_available = 25;
  repeated string capabilities = 26;
}
